name: Download binaries

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Publish
      run: |
        dotnet publish app/GHelper.sln --configuration Release --runtime win-x64 -p:PublishSingleFile=true --no-self-contained
        powershell Compress-Archive app/bin/x64/Release/net8.0-windows/win-x64/publish/GHelper.exe GHelper.zip
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GHelper-artifacts
        path: |
          app/bin/x64/Release/net8.0-windows/win-x64/publish/GHelper.exe
          GHelper.zip
